openapi: 3.0.3
info:
  title: SDF Protocol Mapping
  description: |-
    SDF Protocol Mapping. When adding a
    new protocol mapping please add a reference to the protocol map
    for all the schemas in this file.
  version: 0.10.0
externalDocs:
  description: SDF Protocol Mapping IETF draft
  url: https://datatracker.ietf.org/doc/draft-ietf-asdf-sdf-protocol-mapping/

paths: {}

components:
  schemas:
# Protocol Mapping

## Common protocol map
    CommonProtocolMap:
      oneOf:
      - $ref: './ProtocolMap-BLE.yaml#/components/schemas/ProtocolMap-BLE'
      - $ref: './ProtocolMap-Zigbee.yaml#/components/schemas/ProtocolMap-Zigbee'

## Different protocol mapping for reading & writing an affordance
    DistinctProtocolMap:
      type: object
      properties:
        read:
          oneOf:
          - $ref: './ProtocolMap-BLE.yaml#/components/schemas/ProtocolMap-BLE'
          - $ref: './ProtocolMap-Zigbee.yaml#/components/schemas/ProtocolMap-Zigbee'
        write:
          oneOf:
          - $ref: './ProtocolMap-BLE.yaml#/components/schemas/ProtocolMap-BLE'
          - $ref: './ProtocolMap-Zigbee.yaml#/components/schemas/ProtocolMap-Zigbee'
          
## Protocol Map 
    ProtocolMap:
      type: object
      properties:
        sdfProtocolMap:
          oneOf:  
            - $ref: '#/components/schemas/CommonProtocolMap'
            - $ref: '#/components/schemas/DistinctProtocolMap'