EventStatusResponseArray = [* EventStatusResponse]

; Success item = { event, instanceId }
EventStatusResponse = {
  event: text,        ; SDF global name of the event (absolute URI with fragment)
  instanceId: text    ; UUID (as text)
}
