GroupEventStatusResponseArray = [* GroupEventStatusResponse]

GroupEventSuccessResponse = { event: text, deviceId: text }

; Each item is either an event+deviceId success or a GroupFailureResponse
GroupEventStatusResponse = (GroupEventSuccessResponse // GroupFailureResponse)

GroupFailureResponse = {
  FailureResponse,
  ? deviceId: text
}
