; Group Trigger status response array and item shape

GroupTriggerStatusResponseArray = [* GroupTriggerResponse]

GroupTriggerResponse = {
  SdfReference,
  ? action: text,      ; NIPC action operation to execute
  deviceId: text     ; UUID (as text)
}
