PropertyValueResponseArray = [* PropertyValueResponseArrayItem]

PropertyValueResponseArrayItem = ( SuccessResponse // FailureResponse )

; Minimal success shape (may be extended)
SuccessResponse = {
  ? status: uint
}
