; Trigger status response array and item shape

TriggerStatusResponseArray = [* TriggerResponse]

TriggerResponse = {
  eventName: text,      ; SDF event name
  ? action: text,      ; NIPC action operation to execute
  instanceId: text     ; UUID (as text)
}
